version: '3.7'

services:

  wiremock:
    image: rodolpheche/wiremock:2.19.0
    volumes:
      - type: bind
        source: ./wiremock
        target: /home/wiremock
    command: --port=8889 --global-response-templating
    ports:
      - "8889:8889"